# # Generated by Django 3.0.3 on 2020-03-23 09:20
#
# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('tutare', '0002_useraccount'),
#     ]
#
#     operations = [
#         migrations.CreateModel(
#             name='ContactUs',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('name', models.CharField(blank=True, max_length=50)),
#                 ('email', models.EmailField(max_length=254)),
#                 ('phone', models.CharField(blank=True, max_length=15)),
#                 ('message', models.TextField()),
#                 ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
#             ],
#             options={
#                 'verbose_name_plural': 'Contact Us',
#             },
#         ),
#     ]
