# Generated by Django 3.0.3 on 2020-03-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutare', '0003_auto_20200303_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=25),
        ),
    ]
